# AirBnB NY Locations Data Case Study

In this final project, you task will be to take the data provided and find evidance to answer the following questions.

1. Which hosts are the busiest and why?
2. How many neighborhood groups are available and which shows up the most?
3. Are private rooms the most popular in manhattan?
4. Which hosts are the busiest and based on their reviews?
5. Which neighorhood group has the highest average price?
6. Which neighborhood group has the highest total price?
7. Which top 5 hosts have the highest total price?
8. Who currently has no (zero) availability with a review count of 100 or more?
9. What host has the highest total of prices and where are they located?
10. When did Danielle from Queens last receive a review?

You will be given **4 hours** to complete this assignment. 
**Be Advised** I will go dark for this intire assignment time period. That said, any questions that you would like to ask about the data, or the project **MUST** be asked before the time starts. Once the time has started, I can no longer give information.

This is to similate what you will face when you are out in the wild. 

Happy Coding!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
ab = pd.read_csv('AB_NYC_2019.csv')
ab.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [189]:
ab["booked"] = 365 - ab["availability_365"]
ab_booked = ab.groupby(["host_id", "host_name"]).sum()["booked"].sort_values(ascending = False)
ab_booked

# Blueground, Sonder (NYC), and Kazuya have the most currently booked nights with 25796, 20767, and 17358 booked nights respectively.

host_id    host_name        
107434423  Blueground           25796
219517861  Sonder (NYC)         20767
137358866  Kazuya               17358
19303369   Hiroki               13049
61391963   Corporate Housing    11200
                                ...  
25479861   Michael                  0
186325219  Kenneth                  0
229693987  0123                     0
23718461   Ingrid                   0
223248121  Julia                    0
Name: booked, Length: 37439, dtype: int64

In [32]:
# How many neighborhood groups are available and which shows up the most?

ab_ngcount = ab.groupby("neighbourhood_group", as_index=False).count().sort_values("id", ascending=False).reset_index(drop=True)
print(len(ab_ngcount))
print(ab_ngcount.loc[0][0])
ab_ngcount

# There are five neighborhood groups and Manhattan appears the most


5
Manhattan


neighbourhood_group     id   name  host_id  host_name  neighbourhood  \
0           Manhattan  21661  21652    21661      21652          21661   
1            Brooklyn  20104  20098    20104      20095          20104   
2              Queens   5666   5666     5666       5664           5666   
3               Bronx   1091   1090     1091       1090           1091   
4       Staten Island    373    373      373        373            373   

   latitude  longitude  room_type  price  minimum_nights  number_of_reviews  \
0     21661      21661      21661  21661           21661              21661   
1     20104      20104      20104  20104           20104              20104   
2      5666       5666       5666   5666            5666               5666   
3      1091       1091       1091   1091            1091               1091   
4       373        373        373    373             373                373   

   last_review  reviews_per_month  calculated_host_listings_count  \
0        16632              16632                           21661   
1        16447              16447                           20104   
2         4574               4574                            5666   
3          876                876                            1091   
4          314                314                             373   

   availability_365  
0             21661  
1             20104  
2              5666  
3              1091  
4               373

In [41]:
# Are private rooms the most popular in manhattan?

ab_man_rooms = ab.groupby(["neighbourhood_group","room_type"]).count().loc['Manhattan'].sort_values("id", ascending=False)
ab_man_rooms

# Entire home/apt is the most popular in Manhattan


id   name  host_id  host_name  neighbourhood  latitude  \
room_type                                                                    
Entire home/apt  13199  13193    13199      13196          13199     13199   
Private room      7982   7979     7982       7976           7982      7982   
Shared room        480    480      480        480            480       480   

                 longitude  price  minimum_nights  number_of_reviews  \
room_type                                                              
Entire home/apt      13199  13199           13199              13199   
Private room          7982   7982            7982               7982   
Shared room            480    480             480                480   

                 last_review  reviews_per_month  \
room_type                                         
Entire home/apt         9967               9967   
Private room            6309               6309   
Shared room              356                356   

                 calculated_host_listings_count  availability_365  
room_type                                                          
Entire home/apt                           13199             13199  
Private room                               7982              7982  
Shared room                                 480               480

In [57]:
# Which hosts are the busiest and based on their reviews?

ab_host_busy = ab.groupby(["host_id","host_name"]).count().sort_values('number_of_reviews', ascending=False)["number_of_reviews"]
ab_host_busy

# Sonder (NYC), Blueground and Kara are the busiest host based on number of reviews.

host_id    host_name     
219517861  Sonder (NYC)      327
107434423  Blueground        232
30283594   Kara              121
137358866  Kazuya            103
16098958   Jeremy & Laura     96
                            ... 
13543967   Paulina             1
13541655   Michael             1
13540183   Ashley              1
13538150   Mariana             1
274321313  Kat                 1
Name: number_of_reviews, Length: 37439, dtype: int64

In [60]:
#Which neighorhood group has the highest average price?

ab_ng_hap = ab.groupby("neighbourhood_group").mean().sort_values("price", ascending=False)['price']
ab_ng_hap

# Manhattan has the highest average price

neighbourhood_group
Manhattan        196.875814
Brooklyn         124.383207
Staten Island    114.812332
Queens            99.517649
Bronx             87.496792
Name: price, dtype: float64

In [67]:
# Which neighbor hood group has the highest total price?

# Finding the sum of all prices in each neighborhood group

ab_htp = ab.groupby("neighbourhood_group").sum().sort_values("price", ascending=False)["price"]
ab_htp

# Manhattan has the highest sum of listing prices


# Finding the neighborhood with the most expensive listing

ab_hp = ab.sort_values("price", ascending=False)[["neighbourhood_group", "price"]].reset_index(drop=True)
ab_hp

# The most expensive listing is a tie between Queens, Brooklyn, and Manhattan at $10,000.

neighbourhood_group  price
0                  Queens  10000
1                Brooklyn  10000
2               Manhattan  10000
3               Manhattan   9999
4               Manhattan   9999
...                   ...    ...
48890            Brooklyn      0
48891            Brooklyn      0
48892               Bronx      0
48893            Brooklyn      0
48894            Brooklyn      0

[48895 rows x 2 columns]

In [71]:
#Which top 5 hosts have the highest total price?

ab_host_htp = ab.groupby(["host_id","host_name"]).sum().sort_values("price", ascending=False).head(5)["price"]
ab_host_htp

# Sonder (NYC), Blueground, Sally, Red Awning, and Kara have the highest sum of listing prices

host_id    host_name   
219517861  Sonder (NYC)    82795
107434423  Blueground      70331
156158778  Sally           37097
205031545  Red Awning      35294
30283594   Kara            33581
Name: price, dtype: int64

In [123]:
# Who currently has no (zero) availability with a review count of 100 or more?

ab_host_reviews = ab.groupby(["host_id","host_name"], as_index = False).count().sort_values("number_of_reviews", ascending=False)
ab_host_reviews_100 = ab_host_reviews[ab_host_reviews["number_of_reviews"] >= 100][["host_id", "host_name", "number_of_reviews"]]
ab_host_reviews_100

host_id     host_name  number_of_reviews
34629  219517861  Sonder (NYC)                327
29393  107434423    Blueground                232
19564   30283594          Kara                121
31064  137358866        Kazuya                103

In [128]:
ab_host_avail = ab.groupby(["host_id","host_name"], as_index=False).sum()[["host_id", "host_name", "availability_365"]]
ab_host_avail

host_id  host_name  availability_365
0           2438      Tasos                 0
1           2571      Teedo                23
2           2787       John              1412
3           2845   Jennifer               720
4           2868   Letha M.               221
...          ...        ...               ...
37434  274273284  Anastasia               180
37435  274298453     Adrien                15
37436  274307600   Jonathan               341
37437  274311461      Scott               176
37438  274321313        Kat                31

[37439 rows x 3 columns]

In [132]:
ab_host_100_avail = ab_host_avail.merge(ab_host_reviews_100, on = "host_id", how = "inner")
ab_host_100_avail

# All hosts with a review count of 100 or more have listings available in the coming year

host_id   host_name_x  availability_365   host_name_y  number_of_reviews
0   30283594          Kara             37924          Kara                121
1  107434423    Blueground             58884    Blueground                232
2  137358866        Kazuya             20237        Kazuya                103
3  219517861  Sonder (NYC)             98588  Sonder (NYC)                327

In [142]:
# What host has the highest total of prices and where are they located?

ab_host_htp.head(1)

host_id    host_name   
219517861  Sonder (NYC)    82795
Name: price, dtype: int64

In [144]:
ab.set_index("host_id").loc[219517861].groupby("neighbourhood_group").count()

# Sonder (NYC) has the highest total of prices ($82,795) and is located in Manhattan.

id  name  host_name  neighbourhood  latitude  longitude  \
neighbourhood_group                                                             
Manhattan            327   327        327            327       327        327   

                     room_type  price  minimum_nights  number_of_reviews  \
neighbourhood_group                                                        
Manhattan                  327    327             327                327   

                     last_review  reviews_per_month  \
neighbourhood_group                                   
Manhattan                    207                207   

                     calculated_host_listings_count  availability_365  
neighbourhood_group                                                    
Manhattan                                       327               327

In [172]:
# When did Danielle from Queens last receive a review?

ab_danielle = ab[(ab["host_name"] == "Danielle") & (ab["neighbourhood_group"] == "Queens")].sort_values("last_review", ascending=False)
ab_danielle[["name", "host_name", "neighbourhood_group", "last_review"]]

# Danielle last receieved a review on July 8th, 2019.

name host_name  \
22469  Cute Tiny Room Family Home by LGA NO CLEANING FEE  Danielle   
21517   Sun Room Family Home LGA Airport NO CLEANING FEE  Danielle   
20403  Cozy Room Family Home LGA Airport NO CLEANING FEE  Danielle   
22068                Bed in Family Home Near LGA Airport  Danielle   
7086   Comfy Room Family Home LGA Airport NO CLEANING...  Danielle   
33861  One bedroom with full bed / 1 stop from Manhattan  Danielle   
27021  Quiet & clean 1br haven with balcony near the ...  Danielle   
16349                    ASTORIA APARTMENT OUTDOOR SPACE  Danielle   

      neighbourhood_group last_review  
22469              Queens  2019-07-08  
21517              Queens  2019-07-07  
20403              Queens  2019-07-06  
22068              Queens  2019-07-06  
7086               Queens  2019-07-03  
33861              Queens  2019-06-20  
27021              Queens  2018-01-02  
16349              Queens         NaN

## Further Questions

1. Which host has the most listings?

In [176]:
ab_listings = ab.groupby(["host_id", "host_name"]).count()["id"].sort_values(ascending=False)
ab_listings

# Sonder (NYC) has the most listings (327).

host_id    host_name   
219517861  Sonder (NYC)    327
107434423  Blueground      232
30283594   Kara            121
137358866  Kazuya          103
12243051   Sonder           96
                          ... 
48818023   Sarah             1
48819868   Nick              1
48823036   Fred              1
48823279   Chris             1
2438       Tasos             1
Name: id, Length: 37439, dtype: int64

2. How many listings have completely open availability?

In [184]:
len(ab[ab["availability_365"] == 365])

# 1295 listings have completely open availability.

1295

3. What room_types have the highest review numbers?

In [185]:
ab_type_reviews = ab.groupby("room_type").count()["number_of_reviews"]
ab_type_reviews

# Entire home/apt and Private room have the highest review numbers.

room_type
Entire home/apt    25409
Private room       22326
Shared room         1160
Name: number_of_reviews, dtype: int64

# Final Conclusion

In this cell, write your final conclusion for each of the questions asked.

Also, if you uncovered some more details that were not asked above, please describe them here.

-- Add your conclusion --
1. Blueground, Sonder (NYC), and Kazuya have the most currently booked nights with 25796, 20767, and 17358 booked nights respectively.
2. There are five neighborhood groups and Manhattan appears the most
3. Entire home/apt is the most popular in Manhattan
4. Sonder (NYC), Blueground and Kara are the busiest host based on number of reviews.
5. Manhattan has the highest average price
6. Manhattan has the highest sum of listing prices and the most expensive listing is a tie between Queens, Brooklyn, and Manhattan at 10,000 USD.
7. Sonder (NYC), Blueground, Sally, Red Awning, and Kara have the highest sum of listing prices
8. All hosts with a review count of 100 or more have listings available in the coming year
9. Sonder (NYC) has the highest total of prices (82,795 USD) and is located in Manhattan.
10. Danielle last receieved a review on July 8th, 2019.

1. Sonder (NYC) has the most listings (327).
2. 1295 listings have completely open availability.
3. Entire home/apt and Private room have the highest review numbers.